[workspace]
resolver = "2"
members = [
  "ros-plan-format",
  "ros-plan-compiler",
  "ros2plan",
  "dump2plan",
]

[workspace.dependencies]
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.9"
indexmap = { version = "2.7.0", features = ["serde"] }
