[tool.uv.workspace]
members = ["python/launch2dump", "python/launch2plan"]

[tool.uv.sources]
ros2-introspect = { path = "external/rmw_introspect/ros2_introspect", editable = true }

[tool.uv]
dev-dependencies = []
